providers = ["node"]

[phases.install]
# Noop command
cmds = [":"]

[phases.build]
# Noop command
cmds = [":"]

[phases.load_modules]
depends_on = ['build']
cmds = ['mv /app/server/vendor /app/server/node_modules']
