name: Deploy
on:
  push:
    branches:
      - main
      - appwrite
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - main
          - appwrite

jobs:
  build:
    environment: ${{((inputs.env == 'main' || github.ref_name == 'main') && 'production') || ((inputs.env == 'appwrite' || github.ref_name == 'appwrite') && 'appwrite' || 0)}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: 📥 Setup
        uses: ./.github/actions/setup-job
      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Build core libraries
        run: |
          pnpm --filter @pipelineui/workflow-parser --filter @pipelineui/workflow-languageserver --filter @pipelineui/yaml-editor build

      - name: Build app
        run: |
          pnpm --filter @pipelineui/app build

      - name: Deploy to Railway
        run: |
          cd packages/app
          cp nixpacks.toml .output
          cp .output/server/package.json .output
          cd .output
          RAILWAY_TOKEN=${{ secrets.RAILWAY_DEPLOY_TOKEN }} pnpm railway up -s pipelineui-server -e ${{vars.RAILWAY_ENVIRONMENT}}
