name: Deploy
on:
  push:
    branches:
      - main
      - appwrite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: 📥 Setup
        uses: ./.github/actions/setup-job
      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Build core libraries
        run: |
          pnpm --filter @pipelineui/workflow-parser @pipelineui/workflow-languageserver @pipelineui/yaml-editor build

      - name: Build app
        run: |
          pnpm --filter @pipelineui/app build

      - name: Deploy to Railway (${{env.RAILWAY_ENV}})
        run: |
          cd packages/app
          cp nixpacks.toml .output
          cp .output/server/package.json .output
          cd .output
          pnpm railway environment ${{env.RAILWAY_ENV}}
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} pnpm railway up -s pipelineui-server
        env:
          RAILWAY_ENV: ${{(github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/appwrite' && 'appwrite' || null)}}
